config/routes.rb
Rails.application.routes.draw do

  resources :polls

  get 'vote_here/:url' => 'polls#show_candidates'

  root 'polls#new'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :poll, inverse_of: :candidates
  has_many :votes, dependent: :destroy

  before_destroy :delete_votes, prepend: true

  private

  def delete_votes
    votes.destroy_all
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base

  before_destroy :destroy_candidates, prepend: true

  has_many :votes,inverse_of: :candidate
  has_many :candidates ,inverse_of: :poll, dependent: :destroy

  private

  def destroy_candidates
    candidates.destroy_all
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :poll
  has_one :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController
  def initialize_session
    # perform application setup here
    controller_store[:message_count] = 0
    # check for more https://github.com/websocket-rails/websocket-rails/wiki/WebsocketRails%20Controllers

    # or check https://github.com/lukas2/websockets_chat
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :set_poll_by_url, only: [:show_candidates]
  before_action :auth, only: [:index, :destroy, :update]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
    #todo: show screen to add candidates and vote for them
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to "/vote_here/#{@poll.url}", notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_candidates
    @candidates = @poll.candidates.to_json(include: :votes)
    @title = @poll.title
    @poll_id = @poll.id
    #@votes = @poll.votes
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def set_poll_by_url
      @poll = Poll.where(url: params[:url]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      poll = params.require(:poll).permit(:title, :url)
      # todo: add some random string
      poll['url'] = poll['url'].parameterize.underscore
      return poll
    end

  def auth
    if Rails.application.config.auth_code == params[:auth_code].to_s or
        Rails.application.config.auth_code == session[:auth_code]
      session[:auth_code] = Rails.application.config.auth_code
    else
      puts 'not authorized'
      render :file => 'public/404.html', :status => :unauthorized
    end
  end
end

app/controllers/ws_polls_controller.rb
class WsPollsController < WebsocketRails::BaseController

  # in scalability problems occur, try jruby on trinidad with stomp
  # http://torquebox.org/documentation/2.0.0/stomp.html

  def initialize_session
    # perform application setup here
    controller_store[:message_count] = 0
    # check for more https://github.com/websocket-rails/websocket-rails/wiki/WebsocketRails%20Controllers

    # or check https://github.com/lukas2/websockets_chat
  end

  before_action :set_poll, only: [:revoke_vote, :add_candidate, :vote_for_candidate]
  before_action :set_vote_by_nickname, only: [:vote_for_candidate]

  def add_candidate
    # prevent multiple adds of the same candidate-name for a poll
    if @poll.candidates.where(name: message[:name]).length == 0
      candidates = @poll.candidates.push(Candidate.new(name: message[:name]))

      trigger_success(message: true)

      last_candidate = candidates.last

      return_hash = last_candidate.attributes
      return_hash['votes'] = []

      # todo: add some hashvalue to avoid duplicated urls
      WebsocketRails[@poll.url.to_sym].trigger(:new_candidate, return_hash)
    else
      trigger_failure ({message: "option with name #{message[:name]} exists already for this poll"})
    end
  end

  def revoke_vote
    nickname = message[:nickname]
    vote_id = message[:vote_id]
    candidate_id = message[:candidate_id]

    vote = Vote.where(id: vote_id,nickname: nickname,poll_id: @poll.id, candidate_id: candidate_id)

    if vote.first
      trigger_success ({message: 'vote revoked', attr: vote.first.attributes})
      vote.first.delete
      # trigger update of all channel members
      WebsocketRails[@poll.url.to_sym].trigger(:revoked_vote, {candidate_id: candidate_id, vote: vote.first.attributes})
    else
      trigger_failure ({message: 'not your vote'})
    end
  end

  def vote_for_candidate
    puts 'vote for candate'

    if @vote
      # already voted for this poll
      trigger_failure ({message: 'you already voted for this poll'})
    else
      # create vote on poll
      candidate_id = message[:candidate_id]
      @new_vote = Vote.new(poll_id: @poll.id, candidate_id: candidate_id, nickname: message[:nickname])

      trigger_success(message: @new_vote.save)

      # trigger update of all channel members
      WebsocketRails[@poll.url.to_sym].trigger(:new_vote, {candidate_id: candidate_id, vote: @new_vote})
    end
  end

  private

  def set_poll
    if message[:poll_id]
      @poll = Poll.find(message[:poll_id])
      #else
      #  @poll = Poll.find_by_url(message[:url])
    end
  end

  def set_vote_by_nickname
    if @poll.votes
      @vote = @poll.votes.find_by_nickname(message[:nickname])
    else
      @vote=nil
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidate_helper.rb
module CandidateHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Pollpopulous</title>
  <meta name="description" content="">
  <meta name="keywords" content="ad-hoc voting system">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag '/favicon.ico' %>

  <!-- TODO: put back in when online <script src="//ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.7.2.js"></script>-->
  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>-->
  <%= stylesheet_link_tag    'application', media:'all','data-turbolinks-track'=> true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <!--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>-->
  <!--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/spacelab/bootstrap.min.css"/>-->
  <!--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/amelia/bootstrap.min.css"/>-->


  <!-- Latest compiled and minified JavaScript -->
  <!--<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>-->

  <!--<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400,800' type='text/css'>-->
  <script type="text/javascript">
      $(document).ready(function() {
          console.log('dom ready');
      });
  </script>
</head>
<body class="<%= params[:controller] %>">
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control' %>

    <%= f.label :url %><br>
    <%= f.text_field :url ,class:'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Listing polls</h1>

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:cc="http://creativecommons.org/ns#"
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:svg="http://www.w3.org/2000/svg"
xmlns="http://www.w3.org/2000/svg"
xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
viewBox="0 -256 1950 1950"
id="svg2989"
version="1.1"
inkscape:version="0.48.3.1 r9886"
width="100%"
height="100%"
sodipodi:docname="cloud_font_awesome.svg">
  <metadata
  id="metadata2999">
    <rdf:RDF>
      <cc:Work
      rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
        rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
  id="defs2997" />
  <sodipodi:namedview
  pagecolor="#ffffff"
  bordercolor="#666666"
  borderopacity="1"
  objecttolerance="10"
  gridtolerance="10"
  guidetolerance="10"
  inkscape:pageopacity="0"
  inkscape:pageshadow="2"
  inkscape:window-width="640"
  inkscape:window-height="480"
  id="namedview2995"
  showgrid="false"
  inkscape:zoom="0.13169643"
  inkscape:cx="960"
  inkscape:cy="896"
  inkscape:window-x="0"
  inkscape:window-y="25"
  inkscape:window-maximized="0"
  inkscape:current-layer="svg2989" />
  <g
  transform="matrix(1,0,0,-1,15.186441,1405.4576)"
  id="g2991">
    <path
    d="M 1920,384 Q 1920,225 1807.5,112.5 1695,0 1536,0 H 448 Q 263,0 131.5,131.5 0,263 0,448 0,580 71,689.5 142,799 258,853 q -2,28 -2,43 0,212 150,362 150,150 362,150 158,0 286.5,-88 128.5,-88 187.5,-230 70,62 166,62 106,0 181,-75 75,-75 75,-181 0,-75 -41,-138 129,-30 213,-134.5 84,-104.5 84,-239.5 z"
    id="path2993"
    inkscape:connector-curvature="0"
    style="fill:currentColor" />
  </g>
</svg>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.title %></td>
        <td><%= poll.url %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="cloud">
      <div class="spacer">
        <h1>Create a Poll</h1>


        <p>To create a poll just:</p>
        <ul>
          <li>Enter a title of the Poll e.g. "Best Soy Sauce Brand"</li>
          <li>Enter a hashtag of the Poll e.g. "bssb3000"</li>
          <li>Hit sumbit</li>
          <li>Copy the link</li>
          <li>Share with friends</li>
          <li>Happy Voting!</li>
        </ul>

      </div>
    </div>
  </div>
  <div class="col-md-4 hidden-xs hidden-sm" >
    <%# link_to 'Back', polls_path , class: 'btn btn-default'%>
    <div class="giphy-container polaroid-images">
      <a href="">
        <video class="video " width="320" height="240" controls autoplay>
          <source src="/demo.mp4" type="video/mp4">
          <source src="/demo.webm" type="video/webm">
          Your browser does not support the video tag.
        </video>
      </a>
    </div>
  </div>
  <div class="col-md-12">
    <%= render 'form' %>
  </div>


</div>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poll.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @poll.url %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/polls/show_candidates.html.erb
<div class="Pollpopulous" ng-controller="mainController" ng-init="init(<%= @candidates %>,<%= @poll_id %>)">
  <div class="row">
    <div class="well">
      <div class="row">
        <div class="col-md-2 hidden-xs">
          <nvd3-pie-chart
          margin="{left:0,top:0,bottom:0,right:0}"
          tooltips="true"
          data="data.candidates"
          class="donut-chart"
          showLabels="false"
          x="xFunction()"
          y="yFunction()"
          width="300"
          height="300"
          donut="true"
          donutRatio=".3"
          donutLabelsOutside="false"
          labelType="percent"
          color="color()"
          defs="defs"
          objectequality="true"
          transitionduration="500">
            <svg height="300"></svg>
          </nvd3-pie-chart>


        </div>
        <div class="col-md-2">
          <h1><%= @title %></h1>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-10">
          <div class="row">
            <form id="add_candidate_form" ng-submit="addOption()" role="form">
              <div class="form-group">
                <label for="candidate_title">Option</label>
                <input type="text" class="form-control" id="candidate_title" ng-model="data.optionName" name="location" placeholder="Persian Pizza Prince">
                <label for="nickname">Name</label>
                <input type="text" ng-disabled="data.knownSender" class="form-control" id="nickname" name="nickname" placeholder="your name" ng-model="data.nickname">
              </div>
              <button type="submit" class="btn btn-default">Add new option</button>
            </form>
          </div>
        </div>
        <div class="col-md-5 col-sm-4 hidden-xs">
          <mm-giphy keywords="data.keywords" title="{{'There\'ll be cats!'}}" speed-ms="{{3000}}" api-key="{{'dc6zaTOxFJmzC'}}"></mm-giphy>
        </div>
      </div>
      <!--<alert ng-repeat="alert in alerts" type="alert.type" close="closeAlert($index)">{{alert.msg}}</alert>-->
      <mm-alert-box></mm-alert-box>
    </div>

  </div>
  <div class="list-group">
    <div class="list-group-item" ng-repeat="option in data.candidates | orderBy: '-votes.length' ">
      <div class="row">
        <div class="col-sm-9">
          <h4 class="list-group-item-heading">{{option.name}}</h4>

          <p class="list-group-item-text">Votes:
            <span ng-repeat="vote in option.votes" class="glyphicon glyphicon-star-empty"></span></p>
        </div>
        <div class="col-sm-3">
          <div class="btn-group clearfix" style="float:right;">
            <a class="btn btn-primary btn-xs vote" ng-click="vote(option.id)">Vote here</a>
            <a class="btn btn-default btn-xs" ng-click="revokeVote(option,$index)">Revoke Vote</a>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/polls/show_candidates.html.haml
.pollpopulous{'ng-controller' => 'mainController', 'ng-init' => "init(#{@candidates},#{@poll_id})"}
  .row
    .well
      .row
        .col-md-2.hidden-xs
          %nvd3-pie-chart.donut-chart{:color => 'color()',
          :data => 'data.candidates',
          :donut => 'true',
          :donutlabelsoutside => 'false',
          :donutratio => '.3', :height => '300',
          :labeltype => 'percent',
          :margin => '{left:0,top:0,bottom:0,right:0}',
          :objectequality => 'true',
          :showlabels => 'false',
          :tooltips => 'true',
          :transitionduration => '500',
          :width => '300',
          :x => 'descriptionFunction()',
          :y => 'voteCount()'}
            %svg{:height => '300'}
        .col-md-2
          %h1= @title
        .col-md-3.col-sm-4.col-xs-10
          .row
            %form#add_candidate_form{'ng-submit' => 'addOption()',
            :role => 'form'}
              .form-group
                %label{:for => 'candidate_title'} Option
                %input#candidate_title.form-control{name: 'location',
                'ng-model' => 'data.optionName',
                placeholder: 'Persian Pizza Prince',
                type: 'text'}
                %label{for: 'nickname'} Name
                %input#nickname.form-control{:name => 'nickname', 'ng-disabled' => 'data.knownSender', 'ng-model' => 'data.nickname', :placeholder => 'your name', :type => 'text'}/
              %button.btn.btn-default{:type => 'submit'} Add new option
        .col-md-5.col-sm-4.hidden-xs
          %mm-giphy{'api-key' => "{{'dc6zaTOxFJmzC'}}", :keywords => 'data.keywords',:pipeline => '{{"stickers"}}', 'speed-ms' => '{{3000}}', :title => "{{'So Hungry!'}}"}
      / <alert ng-repeat="alert in alerts" type="alert.type" close="closeAlert($index)">{{alert.msg}}</alert>
      %mm-alert-box
  .list-group
    .list-group-item(ng-repeat= "option in data.candidates | orderBy: '-votes.length'" )
      .row
        .col-sm-9
          %h4.list-group-item-heading
            {{option.name}}
          %p.list-group-item-text
            Votes:
            %span.glyphicon.glyphicon-star-empty{'ng-repeat' => 'vote in option.votes'}
        .col-sm-3
          .btn-group.clearfix(style='float:right;')
            %a.btn.btn-primary.btn-xs.vote{'ng-click' => 'vote(option.id)'} Vote here
            %a.btn.btn-default.btn-xs.revoke{'ng-click' => 'revokeVote(option,$index)'} Revoke Vote